-- MySQL Script generated by MySQL Workbench
-- Tue Dec 22 19:30:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema __projekt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema __projekt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `__projekt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `__projekt` ;

-- -----------------------------------------------------
-- Table `__projekt`.`felgi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `__projekt`.`felgi` (
  `id_felgi` INT NOT NULL AUTO_INCREMENT,
  `producent` VARCHAR(40) NULL DEFAULT NULL,
  `rodzaj` ENUM('stal', 'aluminium', 'magnez', 'wlokno_weglowe') NULL DEFAULT NULL,
  `srednica_cale` INT NULL DEFAULT NULL,
  `szerekosc_cale` INT NULL DEFAULT NULL,
  `ilosc_srob` CHAR(1) NULL DEFAULT NULL,
  `rozstaw_srob_mm` INT NULL DEFAULT NULL,
  `kolor` VARCHAR(40) NULL DEFAULT NULL,
  `stan` ENUM('nowe', 'uzywane') NULL DEFAULT NULL,
  `cena` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_felgi`))
ENGINE = InnoDB
AUTO_INCREMENT = 332
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `__projekt`.`klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `__projekt`.`klienci` (
  `id_klienta` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(40) NULL DEFAULT NULL,
  `nazwisko` VARCHAR(40) NULL DEFAULT NULL,
  `miejscowosc` VARCHAR(40) NULL DEFAULT NULL,
  `adres` VARCHAR(40) NULL DEFAULT NULL,
  `kod_pocztowy` VARCHAR(7) NULL DEFAULT NULL,
  `telefon` INT NULL DEFAULT NULL,
  `samochod` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_klienta`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `__projekt`.`opony`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `__projekt`.`opony` (
  `id_opony` INT NOT NULL,
  `producent` VARCHAR(40) NULL DEFAULT NULL,
  `rodzaj` ENUM('zimowe', 'letnie', 'caloroczne') NULL DEFAULT NULL,
  `profil` INT NULL DEFAULT NULL,
  `srednica_cale` INT NULL DEFAULT NULL,
  `szerokosc_mm` INT NULL DEFAULT NULL,
  `bieznikowane` ENUM('TAK', 'NIE') NULL DEFAULT NULL,
  `indeks_predkosci` CHAR(1) NULL DEFAULT NULL,
  `rok_produkcji` VARCHAR(4) NULL DEFAULT NULL,
  `stan` ENUM('nowe', 'uzywane') NULL DEFAULT NULL,
  `cena` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_opony`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `__projekt`.`sruby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `__projekt`.`sruby` (
  `id_sruby` INT NOT NULL,
  `marka_pojazdu` VARCHAR(40) NULL DEFAULT NULL,
  `typ_gniazda` ENUM('stozkowe', 'kuliste') NULL DEFAULT NULL,
  `srednica_gwintu` VARCHAR(3) NULL DEFAULT NULL,
  `skok_gwintu` DOUBLE NULL DEFAULT NULL,
  `nakretka` ENUM('TAK', 'NIE') NULL DEFAULT NULL,
  PRIMARY KEY (`id_sruby`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `__projekt`.`magazyn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `__projekt`.`magazyn` (
  `opona` INT NULL DEFAULT NULL,
  `ilosc_opon` INT NULL DEFAULT NULL,
  `felga` INT NULL DEFAULT NULL,
  `ilosc_felg` INT NULL DEFAULT NULL,
  `sruba` INT NULL DEFAULT NULL,
  `ilosc_srub` INT NULL DEFAULT NULL,
  CONSTRAINT `1`
    FOREIGN KEY (`opona`)
    REFERENCES `__projekt`.`opony` (`id_opony`),
  CONSTRAINT `2`
    FOREIGN KEY (`felga`)
    REFERENCES `__projekt`.`felgi` (`id_felgi`),
  CONSTRAINT `3`
    FOREIGN KEY (`sruba`)
    REFERENCES `__projekt`.`sruby` (`id_sruby`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `__projekt`.`stanowisko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `__projekt`.`stanowisko` (
  `id_stanowiska` INT NOT NULL AUTO_INCREMENT,
  `stanowisko` VARCHAR(45) NULL DEFAULT NULL,
  `wynagrodzenie` INT NULL DEFAULT NULL,
  `sektor` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_stanowiska`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `__projekt`.`pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `__projekt`.`pracownicy` (
  `id_pracownika` INT NOT NULL,
  `imie` VARCHAR(40) NULL DEFAULT NULL,
  `nazwisko` VARCHAR(40) NULL DEFAULT NULL,
  `stanowisko` INT NULL DEFAULT NULL,
  `data_dolaczenia` DATE NULL DEFAULT NULL,
  `plec` ENUM('kobieta', 'mezczyzna') NULL DEFAULT NULL,
  `pesel` VARCHAR(11) NULL DEFAULT NULL,
  `data_urodzenia` DATE NULL DEFAULT NULL,
  `miejscowosc` VARCHAR(40) NULL DEFAULT NULL,
  `kod_pocztowy` VARCHAR(6) NULL DEFAULT NULL,
  `adres_zamieszkania` VARCHAR(40) NULL DEFAULT NULL,
  `telefon` VARCHAR(9) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pracownika`),
  CONSTRAINT `pracownicy_ibfk_1`
    FOREIGN KEY (`stanowisko`)
    REFERENCES `__projekt`.`stanowisko` (`id_stanowiska`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `__projekt`.`uslugi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `__projekt`.`uslugi` (
  `id_uslugi` INT NOT NULL AUTO_INCREMENT,
  `nazwa_uslugi` VARCHAR(40) NULL DEFAULT NULL,
  `cena` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_uslugi`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `__projekt`.`zlecenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `__projekt`.`zlecenia` (
  `id_zlecenia` INT NOT NULL AUTO_INCREMENT,
  `usluga` INT NULL DEFAULT NULL,
  `klient` INT NULL DEFAULT NULL,
  `stanowisko` INT NULL DEFAULT NULL,
  `data_zlecenia` DATE NULL DEFAULT NULL,
  `zuzyte_materialy` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_zlecenia`),
  CONSTRAINT `zlecenia_ibfk_1`
    FOREIGN KEY (`usluga`)
    REFERENCES `__projekt`.`uslugi` (`id_uslugi`),
  CONSTRAINT `zlecenia_ibfk_2`
    FOREIGN KEY (`klient`)
    REFERENCES `__projekt`.`klienci` (`id_klienta`),
  CONSTRAINT `zlecenia_ibfk_3`
    FOREIGN KEY (`zuzyte_materialy`)
    REFERENCES `__projekt`.`felgi` (`id_felgi`),
  CONSTRAINT `zlecenia_ibfk_4`
    FOREIGN KEY (`stanowisko`)
    REFERENCES `__projekt`.`stanowisko` (`id_stanowiska`),
  CONSTRAINT `zlecenia_ibfk_5`
    FOREIGN KEY (`zuzyte_materialy`)
    REFERENCES `__projekt`.`opony` (`id_opony`),
  CONSTRAINT `zlecenia_ibk_6`
    FOREIGN KEY (`zuzyte_materialy`)
    REFERENCES `__projekt`.`sruby` (`id_sruby`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `__projekt` ;

-- -----------------------------------------------------
-- function ilosc_klientow_z
-- -----------------------------------------------------

DELIMITER $$
USE `__projekt`$$
CREATE DEFINER=`jankowskil`@`localhost` FUNCTION `ilosc_klientow_z`(skad varchar(40)) RETURNS int
BEGIN
DECLARE ile int;
SELECT COUNT(id_klienta) from klienci where miejscowosc=skad into @ile;
RETURN @ile;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure indeks_predkosci_limit
-- -----------------------------------------------------

DELIMITER $$
USE `__projekt`$$
CREATE DEFINER=`jankowskil`@`localhost` PROCEDURE `indeks_predkosci_limit`(in indeks_predkosci VARCHAR(40))
BEGIN

CASE indeks_predkosci
    WHEN "L" THEN SELECT indeks_predkosci AS "limit_predkosci = 120";
    WHEN "M" THEN select indeks_predkosci AS "limit_predkosci = 130";
    WHEN "N" then select indeks_predkosci AS "limit_predkosci = 140";
    WHEN "P" THEN SElect indeks_predkosci AS "limit_predkosci = 150";
    WHEN "Q" THEN Select indeks_predkosci AS "limit_predkosci = 160";
    WHEN "R" THEN SElect indeks_predkosci AS "limit_predkosci = 170";
    WHEN "S" THEN SElect indeks_predkosci AS "limit_predkosci = 180";
    WHEN "T" THEN SElect indeks_predkosci AS "limit_predkosci = 190";
    WHEN "U" THEN SElect indeks_predkosci AS "limit_predkosci = 200";
    WHEN "V" THEN SElect indeks_predkosci AS  "limit_predkosci = 240";
ELSE select indeks_predkosci AS "TO NIE JEST INDEKS PREDKOSCI";
END CASE;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure podwyzka
-- -----------------------------------------------------

DELIMITER $$
USE `__projekt`$$
CREATE DEFINER=`jankowskil`@`localhost` PROCEDURE `podwyzka`(IN id int)
BEGIN
Update stanowisko set wynagrodzenie = 1.1 * wynagrodzenie where id_stanowiska = id;
END$$

DELIMITER ;
USE `__projekt`;

DELIMITER $$
USE `__projekt`$$
CREATE
DEFINER=`jankowskil`@`localhost`
TRIGGER `jankowskil`.`zwolnienia`
AFTER DELETE ON `jankowskil`.`pracownicy`
FOR EACH ROW
SET @zwolnieni_pracownicy = @zwolnieni_pracownicy + 1$$

USE `__projekt`$$
CREATE
DEFINER=`jankowskil`@`localhost`
TRIGGER `jankowskil`.`nieaktualne`
BEFORE INSERT ON `jankowskil`.`zlecenia`
FOR EACH ROW
BEGIN
DELETE FROM zlecenia WHERE year(data_zlecenia) - year(now) > 1;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
